# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

general {
    col.active_border = rgba(798186ee)
    col.inactive_border = rgb(1e1e1e)
    border_size = 2
}

group {
    col.border_active = rgba(798186ee)
    col.border_inactive = rgb(101315)

    groupbar {
        col.active = rgba(00000040)
        col.inactive = rgba(00000020)
        text_color = rgb(ffffff)
        text_color_inactive = rgba(ffffff90)
    }
}

decoration {
    rounding = 6
    rounding_power = 3
      shadow {
      enabled = yes
      range = 16
      color = rgba(00000052)
    }
}

windowrule = match:class ^(vesktop|Vesktop)$, opacity 1.0 override, no_dim on
windowrule = match:class ^(code|VSCode|VSCodium)$, opacity 1.0 override, no_dim on
windowrule = match:class ^(chromium|Chromium|google-chrome|Brave|brave-browser)$, opacity 1.0 override, no_dim on
