-- Generated by scripts/hypr2lua.
-- Source: hyprland.conf

hl.config({
  general = {
    col = {
      active_border = "rgba(798186ee)",
      inactive_border = "rgb(1e1e1e)",
    },
    gaps_in = 4,
    gaps_out = 5,
    border_size = 2,
  },
  group = {
  col = {
    border_active = "rgba(798186ee)",
    border_inactive = "rgb(101315)",
  },
  groupbar = {
    col = {
      active = "rgba(00000040)",
      inactive = "rgba(00000020)",
    },
    text_color = "rgb(ffffff)",
    text_color_inactive = "rgba(ffffff90)",
  },
},
  decoration = {
    rounding = 6,
    rounding_power = 3,
    shadow = {
      enabled = true,
      range = 16,
      color = "rgba(00000052)",
    },
  },
})

hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(vesktop|Vesktop)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(code|VSCode|VSCodium)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(chromium|Chromium|google-chrome|Brave|brave-browser)$",
  },
})
